### ISSUE TITLE
Add quick fix

### ISSUE THREAD

**Issue by UltiRequiem** [nene/eslint-plugin-no-null#3]
It would be very useful

**Comment by nene** [comment]
This can't be fixed safely. Even if 99% of cases it would be safe to replace `null` with `undefined`, there is this 1% where it's not safe and would break the code.

**Comment by UltiRequiem** [comment]
Could you mention one case, please?

**Comment by nene** [comment]
Sure: a library function that expects `null` and doesn't work the same way when called with `undefined`.

For example in React code `null` value is used to create an empty element, using `undefined` won't achieve the same. (Or at least it used to be so).
