### ISSUE TITLE
ignore when testing equality

### ISSUE THREAD

**Issue by carnival187** [nene/eslint-plugin-no-null#4]
it could be great if we could use null when comparing it with value to check some stuff coming from lib or api. i actually use eslint ignore comment  but a rule to avoid it would be nice.

example: 
```
function (data) { // data come from api
  if (data === null) { // throw error
  ...
  }
}
```
thx to considaring it

**Comment by nene** [comment]
Thanks for the suggestion, but I asked the plugin and he said it goes against his mojo. Allowing `null` comparisons would make it easier for `null` values to creep into the whole codebase, and that would really hurt his feelings.

Also, API's returning `null` are no more special than API's expecting `null` as input. Though the former are more common in his experience.

He also suggested other ways of solving this problem, like having a wrapper function/class through which your API calls go and which can shield `null` values from the rest of your code. Then you can put a blindfold on him (he means, disabling the rule) so he can't see that whole file... he really can't stand seeing those `null` values at all.

Yep, he's a highly opinionated plugin :)
